Attribute VB_Name = "mod_memory"
Public G_TOKEN_ERROR
Public G_CHAT_ERROR
Public G_TOKEN_CRASH
Public G_CHAT_CRASH
Public G_TOKEN_DEV
Public G_CHAT_DEV
Public G_TOKEN_SUCCESS
Public G_CHAT_SUCCESS
Public G_VER_SYSTEM
Public G_NAMA_KEDAI_TELE
Public G_INTERVAL_RESET
Public G_COUNTER_CRASH
Public G_VERSION_CONTROL
Public G_SYSTEM_TYPE
Public G_QUERY_1(10)
Public GM_NEXT_PREV
Public G_TOKEN_PASS
Public G_TOKEN_UPDATE_DEV
Public G_CHAT_UPDATE_DEV
Public G_REMOTE_HOSTNAME
Public G_REMOTE_USERNAME
Public G_REMOTE_PASSWORD
Public G_REMOTE_PORT
Public G_REMOTE_DATABASE
Public G_REMOTE_VERSION_ASAL
Public G_VERSION_UPDATE
Public G_UPDATE_QUERY
Public G_LM_ERR_NO
Public G_ERROR_NAIYO
Public G_LOG(5)
Public G_X
Public G_CLIENT_INFO(10)
'G_CLIENT_INFO
'0 : Client Name
'1 : Hostname
'2 : DB Name
'3 : Version In Use



